<?php

function esb_connector_execute_service($service, $operation, $inputparameters) {

    $esbconnector = variable_get('soap');
    $options = array(
        'soap_version' => SOAP_1_1,
        'trace' => 1
    );

    try {
        $client = new SoapClient($esbconnector['url'] . $service . '?wsdl', $options);

        $client->__soapCall($operation,array($inputparameters));

        $resp = $client->__getLastResponse();

        $xml = simplexml_load_string($resp);

        $namespaces = $xml->getNamespaces(TRUE);
        if (array_key_exists('soapenv', $namespaces)) {
            $xml->registerXPathNamespace("soapenv", "http://schemas.xmlsoap.org/soap/envelope/");
            $arreglo = $xml->xpath('//soapenv:Body');
            $respuesta = $arreglo[0];
        } else {
            $respuesta = htmlentities($resp);
        }

    } catch (SoapFault $exception) {
        $respuesta = 'soap fault occured: ' . $exception->getMessage() . '<br/>';
    }

    return $respuesta;
}
