<?php
module_load_include('inc', 'content', 'includes/form');


function eventos_menu() {

    $response = new Hooks;
    return $response->Menu();

}


function eventos_miseventos(){

    $response = new Eventos();
    
    return $response->pageResponse();

}


function eventos_cerrarCurso() {
    drupal_add_js(drupal_get_path('module','eventos') . '/js/cerrarCurso.js');
    return '';

}

function eventos_contenidosEvento() {
    $response = new EventoContent();
    return $response->getContent();
}


function getSituacionFinal($idEstado){
    switch ($idEstado) {
        case 1:
            return '<span class="estado-circulo estado-verde"></span>';
            break;
        case 2:
            return '<span class="estado-circulo estado-rojo"></span>';
            break;
        default:
            return 'N/D';
    }

}


function getEstado($idEstado){
    switch ($idEstado) {
        case 1:
            return '<span class="estado-circulo estado-gris"></span>';
            break;
        case 2:
            return '<span class="estado-circulo estado-amarillo"></span>';
            break;
        case 3:
            return '<span class="estado-circulo estado-azul"></span>';
            break;
        default:
            return '<span class="estado-circulo estado-gris"></span>';
    }

}


function eventos_access_callback()
{
    return !user_is_anonymous(); // hides menu if the user is anonymous
}
